routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\ArticleTypeController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\CapaController;
use App\Http\Controllers\Blog\BlogController;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#rotas blog
Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/blog/article/{id}', [BlogController::class, 'articles'])->name('blog.article');
Route::get('/blog/list/{article_type_id}', [BlogController::class, 'list'])->name('blog.list');

#rota dashboard
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard')->middleware('verified');

#rotas email
Route::get('/email/verify', function () {
    return view('admin.auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

#rotas admin
Route::resource('author', AuthorController::class)->middleware(['auth'])->middleware('verified');
Route::resource('article', ArticleController::class)->middleware(['auth'])->middleware('verified');
Route::resource('articleType', ArticleTypeController::class)->middleware(['auth'])->middleware('verified');
Route::resource('footer', FooterController::class)->middleware(['auth'])->middleware('verified');
Route::resource('capa', CapaController::class)->middleware(['auth'])->middleware('verified');
Route::get('/article/capa/create/{id}', [CapaController::class, 'create'])->middleware('verified')->name('article.capa.create');

require __DIR__.'/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public const _INACTIVE = 0;
    public const _ACTIVE  = 1;
    public const _ARTICLE_TYPE_DEFAULT  = 1;

    use HasFactory;

    protected $table = 'articles';

    protected $attributes = [
        'active' => self::_INACTIVE
    ];

    protected $fillable = ['title', 'summary', 'text', 'file_path', 'file_name','article_type_id', 'active', 'author_id'];

    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    public function articleType()
    {
        return $this->belongsTo(ArticleType::class);
    }

    public function capa()
    {
        return $this->hasOne(Capa::class);
    }
}

app/Models/ArticleType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ArticleType extends Model
{
    public const _INACTIVE = 0;
    public const _ACTIVE  = 1;

    use HasFactory;

    protected $table = 'article_types';

    protected $attributes = [
        'active' => self::_INACTIVE
    ];

    protected $fillable = ['title', 'description', 'active', 'file_path', 'file_name'];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    public static function getAll()
    {
        $articleTypes = articleType::where('active', self::_ACTIVE)
            ->whereNull('deleted_at')
            ->get();

        return $articleTypes;
    }
    
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Handlers\ArticleHandler;
use App\Repositories\IRepositories\ArticleIRepository;
use App\Repositories\IRepositories\AuthorIRepository;
use App\Repositories\IRepositories\ArticleTypeIRepository;
use App\Repositories\ArticleRepository;
use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    protected $_repository;
    protected $_articleTypes;
    protected $_repositoryAuthor;
    protected $_handler;

    public function __construct(
        ArticleIRepository $repository, 
        AuthorIRepository $repositoryAuthor,
        ArticleHandler $handler, 
        ArticleTypeIRepository $repositoryArticleTypes
    )
    {
        $this->_repository = $repository;
        $this->_articleTypes = $repositoryArticleTypes->findActives();
        $this->_repositoryAuthor = $repositoryAuthor;
        $this->_handler = $handler;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->_handler->getMyArticles($this->_repository, $this->_repositoryAuthor);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->_handler->create($this->_articleTypes);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->_handler->store($request, $this->_repository);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->_handler->details($id, $this->_repository);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->_handler->edit($id, $this->_repository, $this->_articleTypes);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->_handler->update($request, $id, $this->_repository, $this->_articleTypes);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->_handler->delete($id, $this->_repository);
    }

    public static function findActives(ArticleRepository $repository, ArticleHandler $handler, $limit = 4)
    {
        return $handler->findActives($repository, $limit);
    }
}

resources/views/admin/article/create.blade.php
@extends('admin.layouts.admintop')
@section('files')
    <!-- Summernote -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<style>
.contact-form h2{
    margin-bottom: 8%;
    margin-top: -10%;
    text-align: center;
    color: #025019;
}

</style>
@endsection

@section('content')
    <div class="container contact-form">
        <div class="contact-image">
            <img src="{{url('/admin/img/logo/conexaonerd.png')}}" alt="ConexãoNerd"/>
        </div>
            <!-- Validation Errors -->
            <x-auth-validation-errors class="mb-4" :errors="$errors" />

            <form method="POST" enctype="multipart/form-data" action=@if (!isset($article) || $article == '') "/article" @else "/article/{{$article->id}}"@endif>
            @csrf
            @if (isset($article))
            @method('PUT')
            @endif
            <h2>Article</h2>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" name="title" id="title" placeholder="Article title" 
                            @if (isset($article) && $article != '')
                                value="{{$article->title}}"
                            @else
                                :value="old('title')"
                            @endif>
                        </div>
                        <div class="form-group">
                            <label for="summary">Summary</label>
                            <input type="text" class="form-control" name="summary" id="summary" placeholder="Article summary" 
                            @if (isset($article) && $article != '')
                                value="{{$article->summary}}"
                            @else
                                :value="old('summary')"
                            @endif>
                        </div>
                        <div class="form-group">
                            <label for="file_path">Image (top article 1500x1000)</label>
                            <input type="file" class="form-control-file" name="file_path" id="file_path">
                            @if(isset($article) && $article != '' && $article->first())
                                <span><h6>Register <img class="caparegister" src={{asset('storage/'.$article->file_path)}} alt=""></h6></span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="article_type_id">Article type</label>
                            <select name="article_type_id" id="article_type_id" class="form-control">
                                @foreach ($articleTypes as $articleType)
                                    <option value="{{$articleType->id}}" 
                                        @if ((isset($article) && $article != '') && $article->article_type_id == $articleType->id)
                                            selected
                                        @endif    
                                    >{{$articleType->title}}</option>
                                @endforeach
                            </select>
                        </div>
                        @if (Auth::user()->is_admin && Auth::user()->is_admin == $_IS_ADMIN)
                        <div class="form-group">
                            <label for="active">Active</label>
                            <select name="active" id="active" class="form-control">
                                <option value="0">No</option>
                                <option value="1" @if (isset($article) && $article != '' && $article->active == $_ACTIVE)
                                    selected
                                @endif>Yes</option>
                            </select>
                        </div>
                        @endif
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
							<label for="text">Article text</label>
							<textarea class="form-control" name="text" id="text">@if (isset($article) && $article != ''){{$article->text}} @else {!!old('text')!!} @endif</textarea>
						</div>
                        <div class="form-group">
							<button type="submit" class="btnContactSubmit my-1">Submit</button>
						</div>
					</div>
				</div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
    $('#text').summernote({
        placeholder: 'Write your article here',
        tabsize: 2,
        height: 200,
        toolbar: [
          ['style', ['style']],
          ['font', ['bold', 'underline', 'clear','fontname']],
          ['fontsize', ['fontsize']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link', 'picture', 'video']],
          ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });
    $('#text').summernote('fontName', 'sans-serif');
    </script>
@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.admintop')

@section('content')

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2 class="indextitle">Manage <b>Article</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="{{route('article.create')}}" class="btn btn-success""><i class="material-icons">&#xE147;</i> <span>New Article</span></a>
                            {{--  <a href="#deleteArticleModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>						  --}}
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th><strong>#</strong></th>
                            <th>Title</th>
                            <th>Type</th>
                            <th>Active</th>
                            <th>Image Top</th>
                            <th>Author</th>
                            <th>Author Email</th>
                            <th class="capaactions">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($articles))
                            @foreach ($articles as $article)
                            <tr>
                                    <td>{{$article->id}}</td>
                                    <td>{{$article->title}}</td>
                                    <td>{{$article->articleType->title}}</td>
                                    <td>@if ($article->active == $_ACTIVE) SIM @else NÃO @endif</td>
                                    <td>{{$article->file_name}}</td>
                                    <td>{{$article->author->first_name}} {{$article->author->last_name}}</td>
                                    <td>{{$article->author->user->email}}</td>
                                    <td>
                                        <a href="{{route('article.edit', $article->id)}}" class="edit" ><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                        <a href="#deleteArticleModal" class="delete" data-toggle="modal" data-id="{{$article->id}}"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                                        @if(isset($article->capa->id) && is_null($article->capa->deleted_at))
                                            <a href="{{route('capa.edit', $article->capa->id)}}" class="editcapa"><i class="material-icons" data-toggle="tooltip" title="EditCapa">image</i></a>
                                        @else
                                            <a href="{{route('article.capa.create', $article->id)}}" class="addcapa"><i class="material-icons" data-toggle="tooltip" title="AddCapa">&#xE147;</i></a>
                                        @endif
                                    </td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>
                <div class="clearfix">
                    <div class="hint-text">Showing <b>{{$articles->count()}}</b> out of <b>{{$articles->total()}}</b> entries</div>
                    <ul class="pagination">
                        <li class="page-item"><a href="{{$articles->previousPageUrl()}}" class="page-link">Previous</a></li>
                        @for ($i = 1;$i <= $articles->lastPage(); $i++)
                        <li class="page-item 
                        @if ($articles->currentPage() == $i)
                            active
                        @endif"><a href="{{$articles->url($i)}}" class="page-link">{{$i}}</a></li>        
                        @endfor
                        <li class="page-item"><a href="{{$articles->nextPageUrl()}}" class="page-link">Next</a></li>
                    </ul>    
                </div>
            </div>
        </div>        
    </div>
    <!-- Delete Modal HTML -->
    <div id="deleteArticleModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="formDeleteArticle" method="POST" action="">
                @csrf
                @if (isset($article) && $article != '')
                @method('DELETE')
                @endif
                    <div class="modal-header">						
                        <h4 class="modal-title">Delete Article</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">					
                        <p>Are you sure you want to delete these Article?</p>
                        <p class="text-warning"><small>This action cannot be undone.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>  

    <script>
        $('.delete').click(function(event){
            var id = $(this).data('id');
            $(".formDeleteArticle").attr("action", "/article/" + id);
        })
    </script>
@endsection