routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\ArticleTypeController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\CapaController;
use App\Http\Controllers\Blog\BlogController;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#rotas blog
Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/blog/article/{id}', [BlogController::class, 'articles'])->name('blog.article');
Route::get('/blog/list/{article_type_id}', [BlogController::class, 'list'])->name('blog.list');

#rota dashboard
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard')->middleware('verified');

#rotas email
Route::get('/email/verify', function () {
    return view('admin.auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

#rotas admin
Route::resource('author', AuthorController::class)->middleware(['auth'])->middleware('verified');
Route::resource('article', ArticleController::class)->middleware(['auth'])->middleware('verified');
Route::resource('articleType', ArticleTypeController::class)->middleware(['auth'])->middleware('verified');
Route::resource('footer', FooterController::class)->middleware(['auth'])->middleware('verified');
Route::resource('capa', CapaController::class)->middleware(['auth'])->middleware('verified');
Route::get('/article/capa/create/{id}', [CapaController::class, 'create'])->middleware('verified')->name('article.capa.create');

require __DIR__.'/auth.php';

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
class Author extends Model
{
    public const _INACTIVE = 0;
    public const _ACTIVE  = 1;

    use HasFactory;

    protected $table = 'authors';

    protected $attributes = [
        'active' => self::_INACTIVE
    ];

    protected $fillable = ['first_name', 'last_name', 'description', 'file_path', 'file_name' , 'active', 'user_id', ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Handlers\AuthorHandler;
use App\Repositories\IRepositories\AuthorIRepository;
use Illuminate\Http\Request;


class AuthorController extends Controller
{
    protected $_repository;
    protected $_handler;

    public function __construct(AuthorIRepository $repository, AuthorHandler $handler)
    {
        $this->_repository = $repository;
        $this->_handler = $handler;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->_handler->get($this->_repository);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->_handler->create($this->_repository);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->_handler->store($request, $this->_repository);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->_handler->details($id, $this->_repository);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->_handler->edit($id, $this->_repository);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->_handler->update($request, $id, $this->_repository);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->_handler->delete($id, $this->_repository);
    }
}

resources/views/admin/author/create.blade.php
@extends('admin.layouts.admintop')

@section('content')
    <div class="container contact-form">
        <div class="contact-image">
            <img src="{{url('/admin/img/logo/conexaonerd.png')}}" alt="ConexãoNerd"/>
        </div>
            <!-- Validation Errors -->
            <x-auth-validation-errors class="mb-4" :errors="$errors" />

            <form class="" method="POST" enctype="multipart/form-data" action=@if (!isset($author) || $author == '' || !$author->first()) "/author" @else "/author/{{$author->id}}"@endif>
            @csrf
            @if (isset($author) && $author != '')
            @method('PUT')
            @endif
            <h2>Author</h2>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input type="text" class="form-control" name="first_name" id="first_name" placeholder="First Name"  
                            @if (isset($author) && $author != '' && $author->first())
                                value="{{$author->first_name}}"
                            @else
                                :value="old('first_name')"
                            @endif>
                        </div>
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Last Name" required
                            @if (isset($author) && $author != '' && $author->first())
                                value="{{$author->last_name}}"
                            @else
                                :value="old('last_name')"
                            @endif>
                        </div>
                        <div class="form-group">
                            <label for="file_path">Avatar</label>
                            <input type="file" class="form-control-file" name="file_path" id="file_path">
                            @if(isset($author) && $author != '' && $author->first() && isset($author->file_path) && $author->file_name != '')
                                <span><h6>Register <img class="caparegister" src={{asset('storage/'.$author->file_path)}} alt=""></h6></span>
                            @endif
                        </div>
                        @if (Auth::user()->is_admin && Auth::user()->is_admin == $_IS_ADMIN)
                        <div class="form-group">
                            <label for="active">Active</label>
                            <select class="form-control" name="active" id="active">
                                <option value="0">No</option>
                                <option value="1" @if (isset($author) && $author != '' && $author->first() && $author->active == $_ACTIVE)
                                    selected
                                @endif>Yes</option>
                            </select>
                        </div>
                        @endif
                        <div class="form-group">
                            <button type="submit" class="btnContactSubmit">Submit</button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" name="description" id="description" rows="10" required>@if (isset($author) && $author != '' && $author->first()){{$author->description}}@else {!!old('description')!!}@endif</textarea>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/author/index.blade.php
@extends('admin.layouts.admintop')

@section('content')

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2 class="indextitle">Manage <b>Author</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="{{route('author.create')}}" class="btn btn-success""><i class="material-icons">&#xE147;</i> <span>My Author</span></a>
                            {{--  <a href="#deleteAuthorModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>						  --}}
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th><strong>#</strong></th>
                            <th>Name</th>
                            <th>Avatar</th>
                            <th>Active</th>
                            <th>Username</th>
                            <th>User Email</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($authors))
                            @foreach ($authors as $author)
                            <tr>
                                    <td>{{$author->id}}</td>
                                    <td>{{$author->first_name}}  {{$author->last_name}}</td>
                                    <td>{{$author->file_name}}</td>
                                    <td>@if ($author->active == $_ACTIVE) SIM @else NÃO @endif</td>
                                    <td>{{$author->user->username}}</td>
                                    <td>{{$author->user->email}}</td>
                                    <td>
                                        <a href="{{route('author.edit', $author->id)}}" class="edit" ><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                        <a href="#deleteAuthorModal" class="delete" data-toggle="modal" data-id="{{$author->id}}"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                                    </td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>
                <div class="clearfix">
                    <div class="hint-text">Showing <b>{{$authors->count()}}</b> out of <b>{{$authors->total()}}</b> entries</div>
                    <ul class="pagination">
                        <li class="page-item"><a href="{{$authors->previousPageUrl()}}" class="page-link">Previous</a></li>
                        @for ($i = 1;$i <= $authors->lastPage(); $i++)
                        <li class="page-item 
                        @if ($authors->currentPage() == $i)
                            active
                        @endif"><a href="{{$authors->url($i)}}" class="page-link">{{$i}}</a></li>        
                        @endfor
                        <li class="page-item"><a href="{{$authors->nextPageUrl()}}" class="page-link">Next</a></li>
                    </ul>    
                </div>
            </div>
        </div>        
    </div>

    <!-- Delete Modal HTML -->
    <div id="deleteAuthorModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="formDeleteAuthor" method="POST" action="">
                @csrf
                @if (isset($author) && $author != '')
                @method('DELETE')
                @endif
                    <div class="modal-header">						
                        <h4 class="modal-title">Delete Author</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">					
                        <p>Are you sure you want to delete these Author?</p>
                        <p class="text-warning"><small>This action cannot be undone.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $('.delete').click(function(event){
            var id = $(this).data('id');
            $(".formDeleteAuthor").attr("action", "/author/" + id);
        })
    </script>

@endsection