routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\ArticleTypeController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\CapaController;
use App\Http\Controllers\Blog\BlogController;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#rotas blog
Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/blog/article/{id}', [BlogController::class, 'articles'])->name('blog.article');
Route::get('/blog/list/{article_type_id}', [BlogController::class, 'list'])->name('blog.list');

#rota dashboard
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard')->middleware('verified');

#rotas email
Route::get('/email/verify', function () {
    return view('admin.auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

#rotas admin
Route::resource('author', AuthorController::class)->middleware(['auth'])->middleware('verified');
Route::resource('article', ArticleController::class)->middleware(['auth'])->middleware('verified');
Route::resource('articleType', ArticleTypeController::class)->middleware(['auth'])->middleware('verified');
Route::resource('footer', FooterController::class)->middleware(['auth'])->middleware('verified');
Route::resource('capa', CapaController::class)->middleware(['auth'])->middleware('verified');
Route::get('/article/capa/create/{id}', [CapaController::class, 'create'])->middleware('verified')->name('article.capa.create');

require __DIR__.'/auth.php';

app/Http/Controllers/Admin/ArticleTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Handlers\ArticleTypeHandler;
use App\Repositories\IRepositories\ArticleTypeIRepository;
use App\Repositories\ArticleTypeRepository;
use Illuminate\Http\Request;
class ArticleTypeController extends Controller
{
    protected $_repository;
    protected $_handler;

    public function __construct(ArticleTypeIRepository $repository, ArticleTypeHandler $handler)
    {
        $this->_repository = $repository;
        $this->_handler = $handler;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->_handler->get($this->_repository);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->_handler->create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->_handler->store($request, $this->_repository);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->_handler->details($id, $this->_repository);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->_handler->edit($id, $this->_repository);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->_handler->update($request, $id, $this->_repository);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->_handler->delete($id, $this->_repository);
    }

    public static function findActives(ArticleTypeRepository $repository, ArticleTypeHandler $handler)
    {
        return $handler->findActives($repository);
    }
}

resources/views/admin/articleType/create.blade.php
@extends('admin.layouts.admintop')

@section('content')
    <div class="container contact-form">
        <div class="contact-image">
            <img src="{{url('/admin/img/logo/conexaonerd.png')}}" alt="ConexãoNerd"/>
        </div>
            <!-- Validation Errors -->
            <x-auth-validation-errors class="mb-4" :errors="$errors" />

            <form method="POST" enctype="multipart/form-data" action=@if (!isset($articleType) || $articleType == '') "/articleType" @else "/articleType/{{$articleType->id}}"@endif>
            @csrf
            @if (isset($articleType) && $articleType != '')
            @method('PUT')
            @endif
            <h2>Article Type</h2>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="title" id="title" placeholder="Title" required 
                        @if (isset($articleType) && $articleType != '')
                            value="{{$articleType->title}}"
                        @else
                            :value="old('title')"
                        @endif>
                    </div>
                    <div class="form-group">
                        <label for="active">Active</label>
                        <select name="active" id="active" class="form-control">
                            <option value="0">No</option>
                            <option value="1" @if (isset($articleType) && $articleType != '' && $articleType->active == $_ACTIVE)
                                selected
                            @endif>Yes</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="file_path">Image</label>
                        <input type="file" class="form-control-file" name="file_path" id="file_path" @if (!isset($articleType) && $articleType = '') required @endif >
                        @if(isset($articleType) && $articleType != '' && $articleType->first())
                            <span><h6>Register <img class="caparegister" src={{asset('storage/'.$articleType->file_path)}} alt=""></h6></span>
                        @endif
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btnContactSubmit my-1">Submit</button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group ">
                        <label for="description">Description</label>
                        <textarea class="form-control" name="description" id="description" rows="5" required>@if (isset($articleType) && $articleType != ''){{$articleType->description}}@else {!!old('description')!!}@endif</textarea>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/articleType/index.blade.php
@extends('admin.layouts.admintop')

@section('content')

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2 class="indextitle">Manage <b>Article Type</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="{{route('articleType.create')}}" class="btn btn-success""><i class="material-icons">&#xE147;</i> <span>New Article Type</span></a>
                            {{--  <a href="#deleteArticleModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>						  --}}
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th><strong>#</strong></th>
                            <th>Title</th>
                            <th>Active</th>
                            <th>Background</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($articleTypes))
                            @foreach ($articleTypes as $articleType)
                            <tr>
                                    <td>{{$articleType->id}}</td>
                                    <td>{{$articleType->title}}</td>
                                    <td>@if ($articleType->active == $_ACTIVE) SIM @else NÃO @endif</td>
                                    <td>{{$articleType->file_name}}</td>
                                    <td>
                                        <a href="{{route('articleType.edit', $articleType->id)}}" class="edit" ><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                        <a href="#deleteArticleTypeModal" class="delete" data-toggle="modal" data-id="{{$articleType->id}}"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                                    </td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>
                <div class="clearfix">
                    <div class="hint-text">Showing <b>{{$articleTypes->count()}}</b> out of <b>{{$articleTypes->total()}}</b> entries</div>
                    <ul class="pagination">
                        <li class="page-item"><a href="{{$articleTypes->previousPageUrl()}}" class="page-link">Previous</a></li>
                        @for ($i = 1;$i <= $articleTypes->lastPage(); $i++)
                        <li class="page-item 
                        @if ($articleTypes->currentPage() == $i)
                            active
                        @endif"><a href="{{$articleTypes->url($i)}}" class="page-link">{{$i}}</a></li>        
                        @endfor
                        <li class="page-item"><a href="{{$articleTypes->nextPageUrl()}}" class="page-link">Next</a></li>
                    </ul>    
                </div>
            </div>
        </div>        
    </div>
    <!-- Delete Modal HTML -->
    <div id="deleteArticleTypeModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="formDeleteArticleType" method="POST" action="">
                @csrf
                @if (isset($articleType) && $articleType != '')
                @method('DELETE')
                @endif
                    <div class="modal-header">						
                        <h4 class="modal-title">Delete Article Type</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">					
                        <p>Are you sure you want to delete these Article Type?</p>
                        <p class="text-warning"><small>This action cannot be undone.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>  

    <script>
        $('.delete').click(function(event){
            var id = $(this).data('id');
            $(".formDeleteArticleType").attr("action", "/articleType/" + id);
        })
    </script>
@endsection