routes/web.php
<?php

use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\Admin\ArticleTypeController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\CapaController;
use App\Http\Controllers\Blog\BlogController;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#rotas blog
Route::get('/', [BlogController::class, 'index'])->name('blog');
Route::get('/blog/article/{id}', [BlogController::class, 'articles'])->name('blog.article');
Route::get('/blog/list/{article_type_id}', [BlogController::class, 'list'])->name('blog.list');

#rota dashboard
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard')->middleware('verified');

#rotas email
Route::get('/email/verify', function () {
    return view('admin.auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

#rotas admin
Route::resource('author', AuthorController::class)->middleware(['auth'])->middleware('verified');
Route::resource('article', ArticleController::class)->middleware(['auth'])->middleware('verified');
Route::resource('articleType', ArticleTypeController::class)->middleware(['auth'])->middleware('verified');
Route::resource('footer', FooterController::class)->middleware(['auth'])->middleware('verified');
Route::resource('capa', CapaController::class)->middleware(['auth'])->middleware('verified');
Route::get('/article/capa/create/{id}', [CapaController::class, 'create'])->middleware('verified')->name('article.capa.create');

require __DIR__.'/auth.php';

app/Models/Footer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Footer extends Model
{
    public const _INACTIVE = 0;
    public const _ACTIVE  = 1;

    use HasFactory;

    protected $table = 'footers';

    protected $fillable = ['name', 'url', 'file_path', 'user', 'active'];
}

app/Http/Controllers/Admin/FooterController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Http\Handlers\FooterHandler;
use App\Repositories\FooterRepository;
use App\Repositories\IRepositories\FooterIRepository;
use Illuminate\Http\Request;

class FooterController extends Controller
{
    protected $_repository;
    protected $_handler;

    public function __construct(FooterIRepository $repository, FooterHandler $handler)
    {
        $this->_repository = $repository;
        $this->_handler = $handler;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->_handler->get($this->_repository);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->_handler->create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->_handler->store($request, $this->_repository, $this->_repository);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $this->_handler->details($id, $this->_repository);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->_handler->edit($id, $this->_repository);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->_handler->update($request, $id, $this->_repository);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->_handler->delete($id, $this->_repository);
    }

    public static function findActives(FooterRepository $repository, FooterHandler $handler, $limit)
    {
        return $handler->findActives($repository, $limit);
    }
}

resources/views/admin/footer/create.blade.php
@extends('admin.layouts.admintop')

@section('content')
    <div class="container contact-form">
        <div class="contact-image">
            <img src="{{url('/admin/img/logo/conexaonerd.png')}}" alt="ConexãoNerd"/>
        </div>
            <!-- Validation Errors -->
            <x-auth-validation-errors class="mb-4" :errors="$errors" />

            <form class="" method="POST" enctype="multipart/form-data" action=@if (!isset($footer) || $footer == '') "/footer" @else "/footer/{{$footer->id}}"@endif>
            @csrf
            @if (isset($footer) && $footer != '')
            @method('PUT')
            @endif
            <h2>Footer</h2>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="url">Url (instagram)</label>
                            <input type="text" class="form-control" name="url" id="url" placeholder="Url (instagram)"  
                            @if (isset($footer) && $footer != '')
                                value="{{$footer->url}}"
                            @else
                                :value="old('url')"
                            @endif>
                        </div>
                        <div class="form-group">
                            <label for="active">Active</label>
                            <select class="form-control" name="active" id="active">
                                <option value="0">No</option>
                                <option value="1" @if (isset($footer) && $footer != '' && $footer->first() && $footer->active == $_ACTIVE)
                                    selected
                                @endif>Yes</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="file_path">Image</label>
                            <input type="file" class="form-control-file" name="file_path" id="file_path" @if (!isset($footer) && $footer = '') required @endif >
                            @if(isset($footer) && $footer != '' && $footer->first())
                                <span><h6>Register <img class="caparegister" src={{asset('storage/'.$footer->file_path)}} alt=""></h6></span>
                            @endif
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btnContactSubmit">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/footer/index.blade.php
@extends('admin.layouts.admintop')

@section('content')

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2 class="indextitle">Manage <b>Footer</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a href="{{route('footer.create')}}" class="btn btn-success""><i class="material-icons">&#xE147;</i> <span>New Footer</span></a>
                            {{--  <a href="#deleteArticleModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>						  --}}
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th><strong>#</strong></th>
                            <th>Url</th>
                            <th>Active</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($footers))
                            @foreach ($footers as $footer)
                            <tr>
                                    <td>{{$footer->id}}</td>
                                    <td>{{$footer->url}}</td>
                                    <td>@if ($footer->active == $_ACTIVE) SIM @else NÃO @endif</td>
                                    <td>
                                        <a href="{{route('footer.edit', $footer->id)}}" class="edit" ><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                        <a href="#deleteFooterModal" class="delete" data-toggle="modal" data-id="{{$footer->id}}"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                                    </td>
                            </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                <hr>
                <div class="clearfix">
                    <div class="hint-text">Showing <b>{{$footers->count()}}</b> out of <b>{{$footers->total()}}</b> entries</div>
                    <ul class="pagination">
                        <li class="page-item"><a href="{{$footers->previousPageUrl()}}" class="page-link">Previous</a></li>
                        @for ($i = 1;$i <= $footers->lastPage(); $i++)
                        <li class="page-item 
                        @if ($footers->currentPage() == $i)
                            active
                        @endif"><a href="{{$footers->url($i)}}" class="page-link">{{$i}}</a></li>        
                        @endfor
                        <li class="page-item"><a href="{{$footers->nextPageUrl()}}" class="page-link">Next</a></li>
                    </ul>    
                </div>
            </div>
        </div>        
    </div>
    <!-- Delete Modal HTML -->
    <div id="deleteFooterModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="formDeleteFooter" method="POST" action="">
                @csrf
                @if (isset($footer) && $footer != '')
                @method('DELETE')
                @endif
                    <div class="modal-header">						
                        <h4 class="modal-title">Delete Footer</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">					
                        <p>Are you sure you want to delete these Footer?</p>
                        <p class="text-warning"><small>This action cannot be undone.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>  

    <script>
        $('.delete').click(function(event){
            var id = $(this).data('id');
            $(".formDeleteFooter").attr("action", "/footer/" + id);
        })
    </script>
@endsection